name: Build & Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build src --configuration Release
    - name: Configuration Tests
      run: dotnet test test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Upload net5 Code Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: /home/runner/work/pulse/pulse/test/coverage.net5.0.opencover.xml
        name: net5-code-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - name: Upload net6 Code Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: /home/runner/work/pulse/pulse/test/coverage.net6.0.opencover.xml
        name: net6-code-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
